// Auto-generated by forte dev

export const routes: Array<{ path: string; component: () => Promise<{ default: (props: any) => any }> }> = [
  { path: "/", component: () => import("./pages/index/page") },
  { path: "/product/:id", component: () => import("./pages/product/[id]/page") },
];
