// Auto-generated by build.rs

#[path = "pages/index/mod.rs"]
mod pages_index;

use anyhow::Result;
use wstd::http::{Error, Request, Response, StatusCode, body::Body};

#[wstd::http_server]
pub async fn main(request: Request<Body>) -> Result<Response<Body>, Error> {
    let (parts, _body) = request.into_parts();
    let headers = parts.headers;
    let path = parts.uri.path();

    if path == "/" {
        match pages_index::handler(headers).await {
            Ok(props) => {
                let stream = forte_json::to_stream(&props);
                return Ok(Response::new(Body::from_stream(stream)));
            }
            Err(e) => {
                return Ok(Response::builder()
                    .status(StatusCode::INTERNAL_SERVER_ERROR)
                    .body(Body::from(format!("Error: {:?}", e)))
                    .unwrap());
            }
        }
    }

    Ok(Response::builder()
        .status(StatusCode::NOT_FOUND)
        .body(Body::empty())
        .unwrap())
}
