name: fn0
description: FaaS Platform
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
packages:
  b2:
    source: terraform-provider
    version: 1.0.2
    parameters:
      - backblaze/b2
